// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs_jMoFGq6ZK0mScFOWf_0fhvAqPfLZ0Y',
    appId: '1:1071061181382:web:1d0961dbf0dba8c29ac8c7',
    messagingSenderId: '1071061181382',
    projectId: 'chatflutter-2a02c',
    authDomain: 'chatflutter-2a02c.firebaseapp.com',
    storageBucket: 'chatflutter-2a02c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFafh7fx9V8-nA__SWLqPuKFffxVDHXlI',
    appId: '1:1071061181382:android:d1da496966de41359ac8c7',
    messagingSenderId: '1071061181382',
    projectId: 'chatflutter-2a02c',
    storageBucket: 'chatflutter-2a02c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDyiT1NwBu3CMKOzTF_5y_m9EuiUAJ8OA',
    appId: '1:1071061181382:ios:51825ae204a4a78d9ac8c7',
    messagingSenderId: '1071061181382',
    projectId: 'chatflutter-2a02c',
    storageBucket: 'chatflutter-2a02c.appspot.com',
    androidClientId: '1071061181382-7jn3iti5jhvfqjca6vheda52ukn00p7b.apps.googleusercontent.com',
    iosClientId: '1071061181382-d5rm58hr43f4qud2sm9rab7uhslcohuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.au',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDyiT1NwBu3CMKOzTF_5y_m9EuiUAJ8OA',
    appId: '1:1071061181382:ios:51825ae204a4a78d9ac8c7',
    messagingSenderId: '1071061181382',
    projectId: 'chatflutter-2a02c',
    storageBucket: 'chatflutter-2a02c.appspot.com',
    androidClientId: '1071061181382-7jn3iti5jhvfqjca6vheda52ukn00p7b.apps.googleusercontent.com',
    iosClientId: '1071061181382-d5rm58hr43f4qud2sm9rab7uhslcohuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.au',
  );
}
